### ISSUE TITLE
`window` is not defined - running in Node env

### ISSUE THREAD

**Issue by jaslakson** [evgenyrodionov/redux-logger#187]
While rendering server-side in node environment - getting the following error:

```
2016-10-28T20:32:49.683803+00:00 app[web.1]: /app/node_modules/redux-logger/lib/defaults.js:8
2016-10-28T20:32:49.683814+00:00 app[web.1]:   logger: undefined && undefined.console || window && window.console,
2016-10-28T20:32:49.683815+00:00 app[web.1]:                                             ^
2016-10-28T20:32:49.683816+00:00 app[web.1]: 
2016-10-28T20:32:49.683817+00:00 app[web.1]: ReferenceError: window is not defined
2016-10-28T20:32:49.683817+00:00 app[web.1]:     at Object.<anonymous> (/app/node_modules/redux-logger/lib/defaults.js:8:45)
2016-10-28T20:32:49.683818+00:00 app[web.1]:     at Module._compile (module.js:570:32)
2016-10-28T20:32:49.683819+00:00 app[web.1]:     at Module._extensions..js (module.js:579:10)
2016-10-28T20:32:49.683819+00:00 app[web.1]:     at Object.require.extensions.(anonymous function) [as .js] (/app/node_modules/babel-register/lib/node.js:152:7)
2016-10-28T20:32:49.683820+00:00 app[web.1]:     at Module.load (module.js:487:32)
2016-10-28T20:32:49.683821+00:00 app[web.1]:     at tryModuleLoad (module.js:446:12)
2016-10-28T20:32:49.683821+00:00 app[web.1]:     at Function.Module._load (module.js:438:3)
2016-10-28T20:32:49.683822+00:00 app[web.1]:     at Function.cls_wrapMethod [as _load] (/app/node_modules/newrelic/lib/shimmer.js:247:38)
2016-10-28T20:32:49.683823+00:00 app[web.1]:     at Module.require (module.js:497:17)
2016-10-28T20:32:49.683823+00:00 app[web.1]:     at require (internal/module.js:20:19)
2016-10-28T20:32:49.683824+00:00 app[web.1]:     at Object.<anonymous> (/app/node_modules/redux-logger/lib/index.js:13:17)
2016-10-28T20:32:49.683825+00:00 app[web.1]:     at Module._compile (module.js:570:32)
2016-10-28T20:32:49.683825+00:00 app[web.1]:     at Module._extensions..js (module.js:579:10)
2016-10-28T20:32:49.683826+00:00 app[web.1]:     at Object.require.extensions.(anonymous function) [as .js] (/app/node_modules/babel-register/lib/node.js:152:7)
2016-10-28T20:32:49.683827+00:00 app[web.1]:     at Module.load (module.js:487:32)

```

**Comment by doronpr** [comment]
Fixed in this PR: https://github.com/evgenyrodionov/redux-logger/pull/188/commits

**Comment by evgenyrodionov** [comment]
Thanks, @doronpr!

Sorry for that problems, I'll be more careful

**Comment by sorahn** [comment]
Thanks for the quick turnaround :)
