### ISSUE TITLE
Export the default logger

### ISSUE THREAD

**Issue by borela** [evgenyrodionov/redux-logger#190]
Not really an issue, just a suggestion as in most cases the default options are ok:

```Javascript
import thunk from 'redux-thunk';
import logger from 'redux-logger';

// ...
applyMiddleware(thunk, logger):
```

And then to import the actual function you would:

```Javascript
import {createLogger} from 'redux-logger';
```

**Comment by MartinMajewski** [comment]
With TS 2.14.1 the typings do not work at all.

1. With default typings: 

```
[ts] Module '"/Users/martinmajewski/Documents/Development/ElectronApps/CapLiper/node_modules/@types/redux-logger/index"' has no exported member 'createLogger'.
```

2. Editing the typings to

```
...
declare namespace createLogger { }
declare function createLogger(options?: ReduxLoggerOptions): Redux.Middleware;
export default createLogger;
```

and importing like so

```
import { Middleware } from 'redux;
import createLogger from 'redux-logger'

...

let loggerMiddleware: Middleware = createLogger()

...

this.ngRedux.configureStore(
      CombinedReducer,
      AppState.Instance,
      [ loggerMiddleware ],
      enhancers);
```

works on compile-time, but crashes on runtime with the error

```
zone.js:392Unhandled Promise rejection: redux_logger_1.default is not a function ; Zone: <root> ; Task: Promise.then ; Value: TypeError: redux_logger_1.default is not a function(…) TypeError: redux_logger_1.default is not a function
    at new AppModule (file:///Users/martinmajewski/Documents/Development/ElectronApps/CapLiper/app/build/app.bundle.js:73:55)
    at NgModuleInjector.AppModuleInjector.createInternal (/AppModule/module.ngfactory.js:126:24)
    at NgModuleInjector.create (file:///Users/martinmajewski/Documents/Development/ElectronApps/CapLiper/app/build/vendor.bundle.js:36452:81)
    at NgModuleFactory.create (file:///Users/martinmajewski/Documents/Development/ElectronApps/CapLiper/app/build/vendor.bundle.js:36426:23)
    at file:///Users/martinmajewski/Documents/Development/ElectronApps/CapLiper/app/build/vendor.bundle.js:35998:66
    at ZoneDelegate.invoke (file:///Users/martinmajewski/Documents/Development/ElectronApps/CapLiper/app/build/polyfills.bundle.js:8959:27)
    at Object.onInvoke (file:///Users/martinmajewski/Documents/Development/ElectronApps/CapLiper/app/build/vendor.bundle.js:31960:42)
    at ZoneDelegate.invoke (file:///Users/martinmajewski/Documents/Development/ElectronApps/CapLiper/app/build/polyfills.bundle.js:8958:33)
    at Zone.run (file:///Users/martinmajewski/Documents/Development/ElectronApps/CapLiper/app/build/polyfills.bundle.js:8843:44)
    at NgZone.run (file:///Users/martinmajewski/Documents/Development/ElectronApps/CapLiper/app/build/vendor.bundle.js:31829:67)
    at PlatformRef_._bootstrapModuleFactoryWithZone (file:///Users/martinmajewski/Documents/Development/ElectronApps/CapLiper/app/build/vendor.bundle.js:35996:28)
    at file:///Users/martinmajewski/Documents/Development/ElectronApps/CapLiper/app/build/vendor.bundle.js:36047:64
    at ZoneDelegate.invoke (file:///Users/martinmajewski/Documents/Development/ElectronApps/CapLiper/app/build/polyfills.bundle.js:8959:27)
    at Zone.run (file:///Users/martinmajewski/Documents/Development/ElectronApps/CapLiper/app/build/polyfills.bundle.js:8843:44)
    at file:///Users/martinmajewski/Documents/Development/ElectronApps/CapLiper/app/build/polyfills.bundle.js:9239:58consoleError @ zone.js:392
zone.js:394Error: Uncaught (in promise): TypeError: redux_logger_1.default is not a function(…)consoleError @ zone.js:394
```

The funniest thing: It is enough to import redux-logger to get this error, even without using it as middleware.

**Comment by evgenyrodionov** [comment]
@MartinMajewski we don't maintain redux-logger's typescript typings

**Comment by evgenyrodionov** [comment]
Done in [2.9.0](https://github.com/evgenyrodionov/redux-logger/releases/tag/2.9.0)

**Comment by borela** [comment]
Thank you :D
